server : http://192.168.1.13:5000
threshold : 0.8
delay: 3
monitor:
  # this is single line comment.
  points:
  # x,y,w,h
    - region: [761,253,216,114]
      matchimage: images/OK-15mins-wait.png.png
      check: match
      notify: true
      action: click
      # frequency provides divider for the  
      frequency: 1

    - region: [1147,31,35,35]
      matchimage: images/notify-red.png
      check: match
      notify: true
      action: none
      # frequency provides divider for the 
      frequency: 1